# Generated by Django 3.1.2 on 2020-11-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad', '0002_auto_20201105_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitarbeiter',
            name='austritt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mitarbeiter',
            name='pLZ',
            field=models.CharField(max_length=5),
        ),
    ]
